version: 2


jobs:
  
  build:
    
    docker:
      - image: circleci/python:3.7.0
    
    steps: 
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y python3-mpi4py openmpi-common openmpi-bin libopenmpi-dev
      - run: mpiexec -np 3 python3 -c 'from mpi4py import MPI; print(MPI.COMM_WORLD.Get_size(), MPI.COMM_WORLD.Get_rank())'
